---
- hosts: 18.170.74.197

#  vars:
#    extend_vg_name: 'samplevg'
#    extend_lv_name: 'samplelv'
#    require_lv_size: '1000M'
  
 
  tasks:
    - name: extending existing filesystem
      command: "lvextend -L+{{ require_lv_size }} /dev/{{ extend_vg_name }}/{{ extend_lv_name }} -r"
