---
- name: Event Viewer log backup 
  hosts: all
  vars:
    log_location: 'C:/backup/logs'
    
  
  tasks:
    - name: create the Install directory in C drive
      win_file:
        path: "{{ log_location }}"
        state: directory

    - name: Execute Script
      ansible.builtin.script: /tmp/bkp_events.bat "{{ log_location }}"

